# Generated by Django 3.2.9 on 2022-01-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0007_multiimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_no', models.CharField(help_text='Enter Sale Order Number', max_length=13, unique=True, verbose_name='Sale no')),
                ('quantity', models.ImageField(blank=True, default='0', null=True, upload_to='')),
                ('price', models.FloatField(blank=True, default='0', null=True)),
                ('total_amt', models.FloatField(editable=False, null=True, verbose_name='Total amount')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('sale_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.customer')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.item')),
            ],
            options={
                'verbose_name_plural': '2. Sale',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(help_text='Enter Purchase Order Number', max_length=13, unique=True, verbose_name='PO no')),
                ('quantity', models.ImageField(blank=True, default='0', null=True, upload_to='')),
                ('price', models.FloatField(blank=True, default='0', null=True)),
                ('total_amt', models.FloatField(editable=False, null=True, verbose_name='Total amount')),
                ('remaining_amt', models.FloatField(editable=False, null=True, verbose_name='Remaining amount')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('pur_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.item')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.vendor')),
            ],
            options={
                'verbose_name_plural': '1. Purchase Order',
            },
        ),
    ]
