# Generated by Django 3.2.9 on 2022-01-24 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220124_1319'),
        ('inventory_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_qty', models.PositiveIntegerField(default=0, editable=False, null=True)),
                ('sale_qty', models.PositiveIntegerField(default=0, editable=False, null=True)),
                ('total_bal_qty', models.PositiveIntegerField(editable=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.item')),
                ('purchase', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manage.purchase')),
                ('sale', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manage.sale')),
            ],
            options={
                'verbose_name_plural': '3. Stock Record',
            },
        ),
    ]
