# Generated by Django 3.2.9 on 2022-01-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manage', '0002_auto_20220124_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='remaining_amt',
        ),
    ]
