# Generated by Django 3.2.9 on 2022-01-20 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_auto_20220120_1927'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Issue no')),
                ('issue_qty', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_dte', models.DateTimeField(auto_now=True, verbose_name='Issue date')),
                ('issue_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Itemname', to='products.item')),
            ],
            options={
                'verbose_name_plural': '2. Stock Issue',
            },
        ),
        migrations.CreateModel(
            name='StockReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Batch no')),
                ('receive_qty', models.FloatField(blank=True, null=True)),
                ('receive_dte', models.DateTimeField(auto_now=True, verbose_name='Receive date')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Item_name', to='products.item')),
                ('receive_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. Stock Receive',
            },
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_receive_qty', models.FloatField(default=0, editable=False, null=True)),
                ('total_issue_qty', models.FloatField(default=0, editable=False, null=True)),
                ('total_bal_qty', models.FloatField(editable=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.item')),
                ('stock_issue', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_issue', to='stock_mg.stockissue')),
                ('stock_receive', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_receive', to='stock_mg.stockreceive')),
            ],
            options={
                'verbose_name_plural': '3. Stock Record',
            },
        ),
    ]
