# Generated by Django 3.2.9 on 2022-01-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_mg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreceive',
            name='receive_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='total_bal_qty',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='total_issue_qty',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='total_receive_qty',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
