# Generated by Django 3.2.9 on 2022-01-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternateaddr',
            options={'verbose_name_plural': '1. Alternate Address'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '2. Customer'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': '3. vendor'},
        ),
    ]
