# Generated by Django 3.2.9 on 2022-02-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
