# Generated by Django 3.2.9 on 2022-02-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220208_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='so',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.saleorder'),
        ),
    ]
