# Generated by Django 3.2.9 on 2022-01-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UoM1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit of Measure')),
                ('short_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='UoM')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Uom1',
            },
        ),
        migrations.CreateModel(
            name='UoM2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit of Measure')),
                ('short_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='UoM')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Uom2',
            },
        ),
    ]
