# Generated by Django 3.2.9 on 2022-01-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_uom1_uom2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brand name')),
                ('logo', models.ImageField(upload_to='static/brands')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': ' Brands ',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Type')),
            ],
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='modify_at',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='uom1',
            name='modify_at',
        ),
        migrations.RemoveField(
            model_name='uom1',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='uom2',
            name='modify_at',
        ),
        migrations.RemoveField(
            model_name='uom2',
            name='modify_by',
        ),
        migrations.CreateModel(
            name='UoMLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modify_on', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(max_length=500)),
                ('Uom1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom', to='products.uom1')),
                ('Uom2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UOM2', to='products.uom1')),
            ],
            options={
                'verbose_name_plural': 'Uom',
            },
        ),
        migrations.CreateModel(
            name='CategoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modify_on', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(max_length=500)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BrandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modify_on', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(max_length=500)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
            options={
                'verbose_name_plural': 'Brand Log',
            },
        ),
    ]
