# Generated by Django 3.2.9 on 2022-01-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220120_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/products')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/products')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/products')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='static/products')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.item')),
            ],
        ),
    ]
