# Generated by Django 3.2.9 on 2022-01-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_multiimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlog',
            options={'verbose_name_plural': '10. Item Log'},
        ),
        migrations.AlterModelOptions(
            name='multiimage',
            options={'verbose_name_plural': '11. Item Images'},
        ),
        migrations.AlterModelOptions(
            name='uomlog',
            options={'verbose_name_plural': '9. Uom Log'},
        ),
    ]
