# Generated by Django 3.2.9 on 2022-01-28 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_auto_20220127_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_on',), 'verbose_name_plural': '6. Items '},
        ),
        migrations.AlterModelOptions(
            name='itemlog',
            options={'verbose_name_plural': 'Item Log'},
        ),
        migrations.RenameField(
            model_name='itemlog',
            old_name='modify_on',
            new_name='last_modify',
        ),
        migrations.RenameField(
            model_name='itemlog',
            old_name='item',
            new_name='parent_item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemlog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='itemlog',
            name='item_no',
        ),
        migrations.RemoveField(
            model_name='itemlog',
            name='modify_by',
        ),
        migrations.AddField(
            model_name='item',
            name='last_log',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.itemlog'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemlog',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
