# Generated by Django 3.2.9 on 2022-01-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220128_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiimage',
            options={'verbose_name_plural': 'Item Images'},
        ),
    ]
